import ContactUs from "@/component/contactPage/contactSection";
import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Brewing Contact Us",
  description: "Generated by Brewing Contact Us",
};
export default function Contact (){
    return(
        <div className="">
            <ContactUs/>
        </div>
    )
}