import React from "react";
import HeroMenu from "@/component/menuPage/HeroSection";
import "../../styles/Menupage.css";
import Image from "next/image";
import CoffeeMenu from "@/component/menuPage/SecondSection";
import BaristasPick from "@/component/menuPage/ThirdSection";
import AddOnNotes from "@/component/menuPage/FourthSection";
import Fifthpage from "@/component/menuPage/Fifthpage";
import Footer from '@/component/Footer/Footer';
import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Brewing Menu",
  description: "Generated by Brewing Menu",
};
const page = () => {
  return (
    <div>
      <HeroMenu />
      <div className="parellex-scrolling">
        <div className="menuPage-sub">
          <CoffeeMenu />
          <Image
            src="/left_blast.svg"
            alt="left-blast"
            width={100}
            height={100}
            quality={100}
            className="left-blast"
          />
          <BaristasPick />
          <Image
            src="/right_blast.svg"
            alt="right-blast"
            width={100}
            height={100}
            quality={100}
            className="right-blast"
          />
        </div>
        <Fifthpage />
          <AddOnNotes />
          <Footer/>
      </div>
    </div>
  );
};

export default page;
