import React from 'react'
import HeroAbout from '@/component/aboutpage/HeroAbout'
import "../../styles/Aboutpage.css";
import Footer from '@/component/Footer/Footer';
import AboutContent from '@/component/aboutpage/SecondAboutPage';
import OurStory from '@/component/aboutpage/ThirdAboutPage';
import Image from "next/image";
import CoreValues from '@/component/aboutpage/FourthAboutPage';
import BehindTheBeans from '@/component/aboutpage/FifthAboutPage';
import SustainabilityCommunity from '@/component/aboutpage/SixthAboutPage';
import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Brewing About",
  description: "Generated by Brewing About",
};
const page = () => {
  return (
    <div>
      <HeroAbout/>
      <div className="parellex-scrolling">
         <div className="aboutPage-sub">
<AboutContent/>
<Image src="/left_blast.svg" alt="left-blast" width={100} height={100} quality={100} className="left-blast"/>    
<OurStory/>
 <Image src="/right_blast.svg" alt="right-blast" width={100} height={100} quality={100} className="right-blast"/>
 <CoreValues/>
 </div>
 <SustainabilityCommunity/>
 <BehindTheBeans/> 
        <Footer/>
      </div>
       
    </div>
  )
}

export default page
