import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/component/Footer/Footer";
import MainLayoutSection from "@/component/General/MainLayout";
export const metadata: Metadata = {
  title: "Brewing",
  description: "Generated by Brewing",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
 <body className="">
     <MainLayoutSection>
        {children}
         {/* <Footer/> */}
         </MainLayoutSection>
      </body>
    </html>
  );
}
